name: Olivier Lacan
url: http://olivierlacan.com
description: "Unfettered thoughts of Olivier Lacan."
permalink: /posts/:title/
highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
    - with_toc_data
    - lax_spacing
    - lax_html_blocks
    - tables
    - footnotes
    - with_toc_data
exclude:
  - Gemfile
  - Gemfile.lock
  - deploy.thor

sass:
  style: :nested
  sass_dir: _sass
gems:
  - jekyll-gist
  - pry
